### PR TITLE
feat(snippets): add more rounded corners

### PR DESCRIPTION
**Pull request by Fadexz**
Adds some changes to round some extra elements.

### CODE REVIEW

**Review by theRealPadster — APPROVED** [review]
@Fadexz It looks like there were merge conflicts. I think your branch may not be up to date with upstream, since the "Rounded Images" snippet was added. Can you just double check that I merged it properly and the snippet looks as intended? We can merge once you approve.

**Review by Fadexz — COMMENTED** [review]
Looks good

**Comment by Fadexz** [comment]
Seems for some reason it wasn't in there from before, so there was a conflict it seems.
Does this only take effect when the marketplace has an update and isn't fetched automatically?

**Comment by theRealPadster** [comment]
> Seems for some reason it wasn't in there from before, so there was a conflict it seems. Does this only take effect when the marketplace has an update and isn't fetched automatically?

Yeah I think it was because you had an existing fork that was behind upstream. You need to sync your fork so it's up to date or it will be behind and could have merge conflicts.

**Comment by Fadexz** [comment]
> > Seems for some reason it wasn't in there from before, so there was a conflict it seems. Does this only take effect when the marketplace has an update and isn't fetched automatically?
> 
> Yeah I think it was because you had an existing fork that was behind upstream. You need to sync your fork so it's up to date or it will be behind and could have merge conflicts.

Yes I tried to do that at the time but it seems it didn't work so I just deleted the local copy to make sure it was all good.

If you don't mind, do you know the answer to my question? Do snippets only get added to the marketplace once a new release of the marketplace occurs? I assume that it is since I don't see it, so it would take maybe a month or so?

**Comment by theRealPadster** [comment]
> If you don't mind, do you know the answer to my question? Do snippets only get added to the marketplace once a new release of the marketplace occurs? I assume that it is since I don't see it, so it would take maybe a month or so?
> 
> I think this answers my question though: #435

If I recall correctly, it fetches and caches the snippets from the GitHub repo. So doesn't need a new release, just needs to be merged in. That issue is different. It's proposing we let users put snippets in a manifest file and host them in their own repo, like how the rest of the marketplace works.

**Comment by Fadexz** [comment]
> If I recall correctly, it fetches and caches the snippets from the GitHub repo. So doesn't need a new release, just needs to be merged in. That issue is different. It's proposing we let users put snippets in a manifest file and host them in their own repo, like how the rest of the marketplace works.

I see. I have tried to do that before and have just now to make sure and I even see the lists populate but I don't see the snippet I added. So you can see it just to clarify? If so i'll have to try a bit harder to make sure I clear everything.

**Comment by theRealPadster** [comment]
I have it in my snippets, but it looks like it's the version that hasn't been updated. I took another look at the code and it looks like it's actually getting them from the local file (your local copy of the marketplace custom app) and not pulling from github. So you'd have to download the latest build of marketplace to update it. We should probably change it to do it remotely, if you want to make a new issue for that.

**Pull request merged**
