### PR TITLE
feat: settings modal styling

### PR DESCRIPTION
**Pull request by theRealPadster**
This PR can be for redesigning the settings modal. Adding dividers like Nord Spotify has seems to help clean things up a little bit, but it would be nice to simplify things more as outlined in #465 

This is what I have so far. 
image

### CODE REVIEW

**Review by kyrie25 — APPROVED** [review]
Looks p good

**Comment by theRealPadster** [comment]
> Looks p good

I'm thinking of using [this library](https://www.npmjs.com/package/react-drag-reorder) to add drag to reorder support for the tabs. Do you think that makes sense to put in this PR or a separate one?

**Comment by kyrie25** [comment]
> > Looks p good
> 
> 
> 
> I'm thinking of using [this library](https://www.npmjs.com/package/react-drag-reorder) to add drag to reorder support for the tabs. Do you think that makes sense to put in this PR or a separate one? 

Since we reworking the modal in the first place I think it's better to do it on this one.

**Comment by theRealPadster** [comment]
I'm just gonna revert the drag and drop thing for now so I can get this PR done. We can try it again later if we want.

**Comment by theRealPadster** [comment]
Looks like this now. Is that fine? (In two parts because it's tall)

image
image

**Review by rxri — APPROVED** [review]

**Pull request merged**
