### PR TITLE
feat(snippets): no music provider

### PR DESCRIPTION
**Pull request by Aimarekin**
Hides the music provider from the lyrics view

### CODE REVIEW

**Review by kyrie25 — APPROVED** [review]
goofy preview image lol

**Comment by kyrie25** [comment]
Resolve Lint issue.

**Comment by theRealPadster** [comment]
Maybe do an X or line through the lyrics provider in the preview image. I think that's what most of the others do. It also might be hard to read the text when it's in the app

**Review by kyrie25 — CHANGES_REQUESTED** [review]
Address Padster's suggestion & resolve conflict

**Pull request closed without merging**
