### PR TITLE
feat(snippets): add `Always show forward button`

### PR DESCRIPTION
**Pull request by Poopooracoocoo**

### CODE REVIEW

**Comment by CharlieS1103** [comment]
@theRealPadster Is the image correct here?

**Comment by theRealPadster** [comment]
> @theRealPadster Is the image correct here?

The path looks fine, or do you mean does it match the rest visually?

**Comment by CharlieS1103** [comment]
> > @theRealPadster Is the image correct here?
> 
> The path looks fine, or do you mean does it match the rest visually?

Yes

**Comment by Poopooracoocoo** [comment]
Feel free to change ofc! :) Just went with a quick screenie

**Comment by theRealPadster** [comment]
Yeah it would be better if there was a bit of whitespace around it, so that it shows up centred in the snippet preview instead of being stretched to fill it end-to-end. 

e.g. It would be good if it was kinda like how this one does it
image

**Comment by theRealPadster** [comment]
> Feel free to change ofc! :) Just went with a quick screenie

I added some whitespace around it. Not sure how to replace the file in a PR. 

always-show-forward

**Review by theRealPadster — APPROVED** [review]

**Pull request merged**
