### PR TITLE
Added Hide Playing Gif Snippet

### PR DESCRIPTION
**Pull request by notPlancha**
Apparently the Now playing gif can be heavy on the cpu, so this snippet hides it. redd.it/x6pvw0

### CODE REVIEW

**Review by CharlieS1103 — CHANGES_REQUESTED** [review]
I'm all good with adding this but maybe remove the part about performance as well as the link to the reddit post because tbh I doubt it.

**Comment by notPlancha** [comment]
Tbh I doubt it too but it was an easy fix that's why I did it
I'll change the text by the morning

**Comment by theRealPadster** [comment]
Can you add like 20-25% whitespace around the edges of the preview? To make it look more consistent with the rest.

**Comment by notPlancha** [comment]
I fixed the ratio to be consistent, hopefully that's what you asked for

**Comment by theRealPadster** [comment]
> I fixed the ratio to be consistent, hopefully that's what you asked for

Not quite what I meant (other icon-only snippets have some transparent padding around the edges), but it looks like it's big enough to fill the snippet preview square, so is probably fine as is.

**Review by theRealPadster — APPROVED** [review]

**Review by CharlieS1103 — APPROVED** [review]

**Pull request merged**
