### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by CharlieS1103**

### CODE REVIEW

**Comment by CharlieS1103** [comment]
@theRealPadster This is probably a good thing to add, seems not of our URL inputs are sanitized which we should probably get on tbh.

**Comment by theRealPadster** [comment]
> @theRealPadster This is probably a good thing to add, seems not of our URL inputs are sanitized which we should probably get on tbh.

Yep. I fixed the one issue but haven't gotten around to the others. Feel free to give it a try 😉

**Comment by CharlieS1103** [comment]
> > @theRealPadster This is probably a good thing to add, seems not of our URL inputs are sanitized which we should probably get on tbh.
> 
> Yep. I fixed the one issue but haven't gotten around to the others. Feel free to give it a try 😉

Will do, whenever I find free time lmfao

**Comment by theRealPadster** [comment]
@CharlieS1103 Fixed everything except for the [the one](https://github.com/spicetify/spicetify-marketplace/security/code-scanning/5) dealing with your `getInvalidCSS` function. It seems to think you should change it to use a regex with the `g` option to ensure it replaces all instances in the string. I'm not really sure what the function does, so I think I'll leave that one to you.

**Review by theRealPadster — CHANGES_REQUESTED** [review]
image

**Pull request merged**
