### PR TITLE
feat(snippets): add FancyLyrics

### PR DESCRIPTION
**Pull request by dantelin2009**
This is a cool snippet I made that improves the Lyrics feature in Spotify. I made it because the lyrics-plus lyrics player stutters a lot, and some lyrics are inaccurate. My snippet even adds some effects that lyrics-plus doesn't have (for example: the current lyric is bigger, animation included). Lyrics-plus also gets colors wrong all the time, so instead of trying to fix lyrics-plus I patched the official one to look pretty
This is how it looks (ignore the font):
image

### CODE REVIEW

**Comment by Tetrax-10** [comment]
add a semi colon before cursor, fix that

**Comment by CharlieS1103** [comment]
This snippet does not do what it says it does and breaks multiple other Spotify components (such as the album art, try popping it out.) So as for now, I'm going to close the PR. If you have another snippet or get this one working feel free to open another one though.

**Comment by dantelin2009** [comment]
Hey @CharlieS1103 What do you mean by that it breaks album art? The css only changes the labels, nothing else. Album art shows up just fine for me. Maybe it is the missing semicolons? Could you please send a screenshot of the issue?
image
Album art shows up just fine for me :/

**Comment by CharlieS1103** [comment]
I don't mean that album art, if you play a song and look at the play bar, try expanding the track cover.

**Pull request closed without merging**
