### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by theRealPadster**
This PR will be for changes for the readme.

### CODE REVIEW

**Comment by theRealPadster** [comment]
@kyrie25 Any idea what happened to the custom apps stuff I added to the README? I don't even see it in the current readme anymore...

**Comment by kyrie25** [comment]
> @kyrie25 Any idea what happened to the custom apps stuff I added to the README? I don't even see it in the current readme anymore...

It is all moved over to the wiki, of which the link is on the Readme.
But for the Custom App I might have forgot to port them over lmao.
Will update the wiki in a sec, no changes are needed to Readme unless you need to do some styling.

**Comment by kyrie25** [comment]
Do feel free to revise the Wiki if you want to, it's fairly easy to edit.

**Comment by theRealPadster** [comment]
Wiki looks really good to me!

**Review by kyrie25 — APPROVED** [review]

**Pull request merged**
