### PR TITLE
feat(snippets): smooth progress/volume bar

### PR DESCRIPTION
**Pull request by Droidiar**
Makes the Progress/Volume bar smooth!

using a very very simple method :3

preview
 the gif is very very slow

### CODE REVIEW

**Review by theRealPadster — CHANGES_REQUESTED** [review]
This seems good to me but what is that icon? Is there anything else that would be more indicative of what the snippet does?

**Comment by Droidiar** [comment]
If I was able to add an animated media I could probably just use the gif I sent but I could make something better if that's out of the picture. 
I was kinda workin with just a 50x50 picture so its bad yeah.

**Comment by theRealPadster** [comment]
@Droidiar How is this?
smooth-progress-bar

**Comment by Droidiar** [comment]
Oh! Thank you, that's really good.

**Review by theRealPadster — APPROVED** [review]

**Pull request merged**
