### PR TITLE
feat: Fix Lyrics Plus Theme Snippet

### PR DESCRIPTION
**Pull request by rahaaatul**

### CODE REVIEW

**Comment by ohitstom** [comment]
what themes does this fix the description, image, and title aren't very descriptive

**Comment by rahaaatul** [comment]
> what themes does this fix the description, image, and title aren't very descriptive

For all themes. It replaces the lyrics' bright background color with the current theme's base color and text color with the current theme's text colors.

**Comment by rxri** [comment]
Just disable the colorful background in Lyrics Plus config and set the variables accordingly

**Comment by rahaaatul** [comment]
🤦wasted so much time on it, when the solution was there all along lol.

Thank you.

**Comment by rxri** [comment]
Happens!

**Pull request closed without merging**
