### PR TITLE
i18n: Add translation support for import/export functionality

### PR DESCRIPTION
**Pull request by theRealPadster**
Enable translation support for import/export modal. Also renames it to "backup modal" and tweaks some of the copy. 

image

image

### CODE REVIEW

**Review by CharlieS1103 — APPROVED** [review]

**Comment by theRealPadster** [comment]
I want to rename the modal to be consistent with the settings menu. Call it `BackupModal` instead of `ImportExportModal`?

**Review by CharlieS1103 — CHANGES_REQUESTED** [review]
We should probably make it work first.

**Comment by theRealPadster** [comment]
> We should probably make it work first.

Fixed

**Comment by xerta555** [comment]
My pr: https://github.com/spicetify/spicetify-marketplace/pull/370

**Review by kyrie25 — APPROVED** [review]

**Pull request merged**
