### PR TITLE
i18n: add catalan translation

### PR DESCRIPTION
**Pull request by Seifer23**

### CODE REVIEW

**Comment by Seifer23** [comment]
Just found out i missed some lines, will update very soon

**Comment by Seifer23** [comment]
Sorry for missing some lines, i started the translation from the [es.json](https://github.com/spicetify/spicetify-marketplace/blob/main/src/resources/locales/es.json) and just found out it's a bit outdated.

**Comment by theRealPadster** [comment]
Thanks for this, looks great, but I think you're missing a comma on line 23. I can merge in once that's fixed 🙂

**Comment by Seifer23** [comment]
Sorry for that, it's now added

**Review by theRealPadster — APPROVED** [review]

**Pull request merged**
