### PR TITLE
chore(issue_template): remove config

### PR DESCRIPTION
**Pull request by SunsetTechuila**
there is already an organization's [one](https://github.com/spicetify/.github/blob/main/.github/ISSUE_TEMPLATE/config.yml)

### CODE REVIEW

**Review by rxri — APPROVED** [review]

**Comment by SunsetTechuila** [comment]
oh, now there are no contact links at all
image
great job, github

**Comment by SunsetTechuila** [comment]
i thought it would work in another way

**Comment by theRealPadster** [comment]
> i thought it would work in another way

Can you revert PR then?

**Comment by SunsetTechuila** [comment]
I will

**Pull request merged**
