### PR TITLE
adding custom Background

### PR DESCRIPTION
**Pull request by byQuexo**
Purple Darth Vadder Background

### CODE REVIEW

**Comment by xerta555** [comment]
Why don't adding an option into the Marketplace options with a toggle to enable/disable the option itself, and a second one to let or change the default URL you purpose ?
It would be more flexible..

**Comment by CharlieS1103** [comment]
> Why don't adding an option into the Marketplace options with a toggle to enable/disable the option itself, and a second one to let or change the default URL you purpose ?
> 
> It would be more flexible..

Bit confused on what you mean by the first part

**Comment by xerta555** [comment]
> > Why don't adding an option into the Marketplace options with a toggle to enable/disable the option itself, and a second one to let or change the default URL you purpose ?
> > It would be more flexible..
> 
> Bit confused on what you mean by the first part

In simple therms: why just don't add an enable/disable option to apply a custom background img ?
A first option to toggle the function and a second one to apply a specific one with an URL.

**Comment by kyrie25** [comment]
> > > Why don't adding an option into the Marketplace options with a toggle to enable/disable the option itself, and a second one to let or change the default URL you purpose ?
> 
> > > It would be more flexible..
> 
> > 
> 
> > Bit confused on what you mean by the first part
> 
> 
> 
> In simple therms: why just don't add an enable/disable option to apply a custom background img ?
> 
> A first option to toggle the function and a second one to apply a specific one with an URL.

That would not be possible using pure CSS/as a snippet, which is what this PR tries to do.

**Comment by CharlieS1103** [comment]
I had an idea to make this viable, let snippets use string and int variables and expand their features a little to allow users to input these

**Comment by kyrie25** [comment]
> I had an idea to make this viable, let snippets use string and int variables and expand their features a little to allow users to input these 

Lol if so just let them use CSS body variables. You can set them using snippets already.

**Comment by theRealPadster** [comment]
Do we let users edit the built-in snippets? Then they could just change the image url

**Comment by CharlieS1103** [comment]
> Do we let users edit the built-in snippets? Then they could just change the image url

Pretty sure we do, but I think basically wrapping css variables in a ui is probably more useable since a lot of users wouldn't want to edit the text

**Comment by Satanarious** [comment]
The [Spicetify Galaxy](https://github.com/harbassan/spicetify-galaxy) theme lets you use custom backgrounds for Home Screen(This is applied to all other pages other than the forth mentioned one) and Playlist Pages. You can maybe request him to add an option for the marketplace. He's quick with the replies and added a feature I requested in a day or two.

**Comment by theRealPadster** [comment]
We could also just add it as an option in the marketplace settings, and use a variable. 

e.g. in the settings modal, have a text entry for adding an image url, and that's saved as `--marketplace-body-background`. Then when that's changed, we set it on body. Or is it possible to have CSS be conditional if a variable exists or not?

**Pull request closed without merging**
