### PR TITLE
fix: handling username with special characters

### PR DESCRIPTION
**Pull request by kyrie25**
i hate powershell
image
More details in spicetify/spicetify-cli#1940

### CODE REVIEW

**Comment by theRealPadster** [comment]
Is it possible to change the config location and potentially break this, or no? I think I'm Linux there's a `$SPICETIFY_CONFIG` variable.

**Review by CharlieS1103 — APPROVED** [review]
i don't know anything about powershell so might as well approve it.

**Comment by CharlieS1103** [comment]
> Is it possible to change the config location and potentially break this, or no? I think in Linux there's a `$SPICETIFY_CONFIG` variable.

powershell is windows only no?

**Comment by theRealPadster** [comment]
> powershell is windows only right?
Yes but I was wondering if there was a variable for Windows that lets you change the config location

**Comment by CharlieS1103** [comment]
> > powershell is windows only right?
> > Yes but I was wondering if there was a variable for Windows that lets you change the config location

Ah understood.

**Comment by Tetrax-10** [comment]
> > Is it possible to change the config location and potentially break this, or no? I think in Linux there's a `$SPICETIFY_CONFIG` variable.
> 
> powershell is windows only right?

Nope you can install PowerShell in both Mac, Linux

[Linux Installation ](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2)
[MacOS Installation ](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2)

**Comment by kyrie25** [comment]
> Nope you can install PowerShell in both Mac, Linux
> 
> 
> 
> [Linux Installation ](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2)
> 
> [MacOS Installation ](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2)
This PowerShell install **script** is for Windows only.

**Comment by kyrie25** [comment]
> 
> 
> > powershell is windows only right?
> 
> Yes but I was wondering if there was a variable for Windows that lets you change the config location
> 
> 
> 
> 

The environment variable is not set nor used on Windows, I checked the CLI install script beforehand.

**Pull request merged**
