### PR TITLE
Improve French translation

### PR DESCRIPTION
**Pull request by xerta555**
Is it possible to add theses following texts in the `en.json` file please ?

Left side:
image
Right side:
image

Thanks.

### CODE REVIEW

**Comment by theRealPadster** [comment]
Looks good to me. Also looks like I missed some linting stuff in a previous merge 🙃 

@CharlieS1103  @kyrie25 What do you guys think about adding translations for Marketplace? The project itself is called "Spicetify Marketplace", so I can see the argument for leaving the product name/brand as-is. But I can also see the viewpoint where it is _a_ marketplace for Spicetify. 

We could add a translation for the second screenshot, but not in the sidebar, since that's hardcoded based on the app name.

**Review by theRealPadster — APPROVED** [review]

**Comment by kyrie25** [comment]
> @CharlieS1103 @kyrie25 What do you guys think about adding translations for "Marketplace"? The project itself is called "Spicetify Marketplace", so I can see the argument for leaving the product name/brand as-is. But I can also see the viewpoint where it is _a_ marketplace for Spicetify.

I can't really see why not, brand names can be adapted to other languages also, so it seems fine to me.

**Comment by theRealPadster** [comment]
Okay, I've added a couple new translation keys in [this commit](https://github.com/spicetify/spicetify-marketplace/commit/3247b00288bf8da328f677fd897a1ee481c06612), if you want to update your PR @xerta555

**Review by theRealPadster — CHANGES_REQUESTED** [review]
Please add `grid.spicetifyMarketplace` and `readmePage.title`.

**Review by theRealPadster — APPROVED** [review]

**Pull request merged**
